# Generated by Django 5.1.15 on 2026-04-28 21:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0007_notif_pref_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('b2c_transaction', 'B2C transaction (consolidated detail)'), ('invoice_snapshot', 'Invoice snapshot'), ('ingestion_source', 'Ingestion source document')], db_index=True, max_length=32)),
                ('related_entity_type', models.CharField(blank=True, max_length=64)),
                ('related_entity_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('parent_invoice_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('s3_object_key', models.CharField(blank=True, max_length=512)),
                ('file_mime_type', models.CharField(blank=True, max_length=128)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('retain_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deletion_pending', models.BooleanField(default=False)),
                ('archived_by_user_id', models.UUIDField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'archive_document',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['organization', 'document_type', '-archived_at'], name='archive_doc_organiz_ae1ebc_idx'), models.Index(fields=['parent_invoice_id'], name='archive_doc_parent__667378_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='archive_doc_related_2a28cd_idx')],
            },
        ),
    ]
