# Generated by Django 5.1.15 on 2026-04-28 05:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0003_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "field_path",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("message", models.CharField(max_length=512)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "validation_issue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "invoice_id"],
                        name="validation__organiz_8238d8_idx",
                    ),
                    models.Index(
                        fields=["invoice_id", "severity"],
                        name="validation__invoice_a64a56_idx",
                    ),
                ],
            },
        ),
    ]
