# Generated by Django 5.1.15 on 2026-04-28 05:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.SlugField(max_length=64, unique=True)),
                ("values", models.JSONField(blank=True, default=dict)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_setting",
                "ordering": ["namespace"],
            },
        ),
    ]
