# Generated by Django 5.1.15 on 2026-04-28 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationCode",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("description_en", models.CharField(max_length=512)),
                ("description_bm", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "db_table": "classification_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CountryCode",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name_en", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "country_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MsicCode",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("description_en", models.CharField(max_length=512)),
                ("description_bm", models.CharField(blank=True, max_length=512)),
                (
                    "parent_code",
                    models.CharField(blank=True, db_index=True, max_length=8),
                ),
            ],
            options={
                "db_table": "msic_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaxTypeCode",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("description_en", models.CharField(max_length=255)),
                ("applies_to_sst_registered", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tax_type_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasureCode",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("description_en", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "unit_of_measure_code",
                "ordering": ["code"],
            },
        ),
    ]
