# Generated by Django 5.1.15 on 2026-04-28 18:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_seed_reference_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_user_id', models.UUIDField(db_index=True)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by_user_id', models.UUIDField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'impersonation_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['staff_user_id', 'ended_at'], name='impersonati_staff_u_182420_idx'), models.Index(fields=['organization_id', 'started_at'], name='impersonati_organiz_334423_idx')],
            },
        ),
    ]
