# Generated by Django 5.1.15 on 2026-04-27 21:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0002_rls_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("service", "Service"),
                            ("staff", "Staff"),
                            ("external", "External"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=128)),
                ("action_type", models.CharField(db_index=True, max_length=128)),
                ("affected_entity_type", models.CharField(blank=True, max_length=64)),
                ("affected_entity_id", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("payload_schema_version", models.IntegerField(default=1)),
                ("content_hash", models.BinaryField(max_length=32)),
                ("chain_hash", models.BinaryField(max_length=32, unique=True)),
                (
                    "signature",
                    models.BinaryField(blank=True, default=bytes, max_length=64),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["organization", "sequence"],
                        name="audit_event_organiz_517ce9_idx",
                    ),
                    models.Index(
                        fields=["action_type", "timestamp"],
                        name="audit_event_action__b91003_idx",
                    ),
                ],
            },
        ),
    ]
