# Generated by Django 5.1.15 on 2026-04-28 09:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_audit_sequence_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainVerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('tampered', 'Tampered'), ('error', 'Error')], max_length=16)),
                ('events_verified', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=16)),
                ('error_detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'chain_verification_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
