# Generated by Django 5.1.15 on 2026-04-28 21:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0007_notif_pref_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('trial', 'Trial'), ('solo', 'Solo'), ('team', 'Team'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], db_index=True, max_length=16)),
                ('monthly_price_cents', models.IntegerField(default=0)),
                ('annual_price_cents', models.IntegerField(default=0)),
                ('billing_currency', models.CharField(default='MYR', max_length=8)),
                ('included_invoices_per_month', models.IntegerField(default=0)),
                ('per_overage_cents', models.IntegerField(default=0)),
                ('included_users', models.IntegerField(default=0)),
                ('included_api_keys', models.IntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible on the public pricing page. Internal-only plans (legacy grandfathered, custom enterprise) set this False.')),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ['tier', 'slug', '-version'],
                'indexes': [models.Index(fields=['is_active', 'is_public'], name='billing_pla_is_acti_ad3f9c_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='uniq_plan_slug_version')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('card', 'Card'), ('fpx', 'FPX (Online banking)')], max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'billing_payment_method',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='billing_pay_organiz_2b3166_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('replaced', 'Replaced')], db_index=True, default='trialing', max_length=16)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=16)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='billing_sub_organiz_e1331c_idx'), models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_684a21_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('invoice_processed', 'Invoice processed'), ('api_call', 'API call'), ('vision_engine_call', 'Vision engine call')], db_index=True, max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('related_entity_type', models.CharField(blank=True, max_length=64)),
                ('related_entity_id', models.CharField(blank=True, max_length=128)),
                ('subscription_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('plan_slug', models.CharField(blank=True, max_length=64)),
                ('plan_version', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'billing_usage_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', 'event_type', '-occurred_at'], name='billing_usa_organiz_93b353_idx'), models.Index(fields=['subscription_id', '-occurred_at'], name='billing_usa_subscri_0171bd_idx')],
            },
        ),
    ]
