# Generated by Django 5.1.15 on 2026-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_annual',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
