# Generated by Django 5.1.15 on 2026-05-02 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_stripe_price_ids'),
        ('identity', '0019_oidc_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('default_enabled', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, db_index=True, max_length=32)),
            ],
            options={
                'db_table': 'billing_feature_flag',
                'ordering': ['category', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagOverride',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='billing.featureflag')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'billing_feature_flag_override',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'flag'], name='billing_fea_organiz_856a19_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'flag'), name='uniq_feature_flag_override_per_org')],
            },
        ),
        migrations.CreateModel(
            name='OverageWaiver',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('waived_invoice_count', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overage_waivers', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_overage_waiver',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='billing_ove_organiz_7fdc00_idx'), models.Index(fields=['subscription', 'period_start'], name='billing_ove_subscri_6820c0_idx')],
            },
        ),
    ]
