# Generated by Django 5.1.15 on 2026-04-28 06:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0003_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMaster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("tin", models.CharField(blank=True, db_index=True, max_length=32)),
                (
                    "tin_verification_state",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("failed", "Failed verification"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                ("tin_last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=64)),
                ("msic_code", models.CharField(blank=True, max_length=8)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("sst_number", models.CharField(blank=True, max_length=32)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "customer_master",
                "ordering": ["-usage_count", "legal_name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "tin"],
                        name="customer_ma_organiz_fddc6a_idx",
                    ),
                    models.Index(
                        fields=["organization", "legal_name"],
                        name="customer_ma_organiz_82d156_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tin__gt", "")),
                        fields=("organization", "tin"),
                        name="customer_master_uniq_org_tin",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemMaster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_name", models.CharField(db_index=True, max_length=512)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("default_msic_code", models.CharField(blank=True, max_length=8)),
                (
                    "default_classification_code",
                    models.CharField(blank=True, max_length=16),
                ),
                ("default_tax_type_code", models.CharField(blank=True, max_length=16)),
                (
                    "default_unit_of_measurement",
                    models.CharField(blank=True, max_length=16),
                ),
                (
                    "default_unit_price_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "item_master",
                "ordering": ["-usage_count", "canonical_name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "canonical_name"],
                        name="item_master_organiz_08fedd_idx",
                    )
                ],
            },
        ),
    ]
