# Generated by Django 5.1.15 on 2026-04-28 04:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0003_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ingestion_job_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        default="outbound",
                        max_length=16,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("credit_note", "Credit note"),
                            ("debit_note", "Debit note"),
                            ("refund_note", "Refund note"),
                            ("self_billed", "Self-billed"),
                        ],
                        default="standard",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracting", "Extracting"),
                            ("enriching", "Enriching"),
                            ("validating", "Validating"),
                            ("ready_for_review", "Ready for review"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("signing", "Signing"),
                            ("submitting", "Submitting"),
                            ("validated", "Validated by LHDN"),
                            ("rejected", "Rejected by LHDN"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="ready_for_review",
                        max_length=24,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=128)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency_code", models.CharField(default="MYR", max_length=3)),
                ("payment_terms_code", models.CharField(blank=True, max_length=32)),
                ("payment_reference", models.CharField(blank=True, max_length=128)),
                ("supplier_legal_name", models.CharField(blank=True, max_length=255)),
                ("supplier_tin", models.CharField(blank=True, max_length=32)),
                (
                    "supplier_registration_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("supplier_msic_code", models.CharField(blank=True, max_length=8)),
                ("supplier_address", models.TextField(blank=True)),
                ("supplier_phone", models.CharField(blank=True, max_length=32)),
                ("supplier_sst_number", models.CharField(blank=True, max_length=32)),
                ("buyer_legal_name", models.CharField(blank=True, max_length=255)),
                ("buyer_tin", models.CharField(blank=True, max_length=32)),
                (
                    "buyer_registration_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("buyer_msic_code", models.CharField(blank=True, max_length=8)),
                ("buyer_address", models.TextField(blank=True)),
                ("buyer_phone", models.CharField(blank=True, max_length=32)),
                ("buyer_sst_number", models.CharField(blank=True, max_length=32)),
                ("buyer_country_code", models.CharField(blank=True, max_length=2)),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "myr_equivalent_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("discount_reason_code", models.CharField(blank=True, max_length=32)),
                ("overall_confidence", models.FloatField(blank=True, null=True)),
                ("per_field_confidence", models.JSONField(blank=True, default=dict)),
                ("structuring_engine", models.CharField(blank=True, max_length=128)),
                ("raw_extracted_text", models.TextField(blank=True)),
                (
                    "lhdn_uuid",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("lhdn_qr_code_url", models.URLField(blank=True)),
                ("signed_xml_s3_key", models.CharField(blank=True, max_length=1024)),
                ("validation_timestamp", models.DateTimeField(blank=True, null=True)),
                ("cancellation_timestamp", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("unit_of_measurement", models.CharField(blank=True, max_length=16)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "unit_price_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "line_subtotal_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("tax_type_code", models.CharField(blank=True, max_length=16)),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "line_total_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("classification_code", models.CharField(blank=True, max_length=16)),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("discount_reason_code", models.CharField(blank=True, max_length=32)),
                ("per_field_confidence", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="submission.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "line_item",
                "ordering": ["invoice", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="invoice_organiz_4f2a87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status"], name="invoice_organiz_b92a54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "invoice_number"],
                name="invoice_organiz_3e314f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lineitem",
            index=models.Index(
                fields=["organization", "invoice"], name="line_item_organiz_488be6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lineitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "line_number"), name="uniq_line_per_invoice"
            ),
        ),
    ]
