# Generated by Django 5.1.15 on 2026-04-28 09:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_seed_roles_and_permissions"),
        ("submission", "0002_rls_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionInboxItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("validation_failure", "Validation failure"),
                            ("structuring_skipped", "Structuring skipped"),
                            ("low_confidence_extraction", "Low-confidence extraction"),
                            ("lhdn_rejection", "Rejected by LHDN"),
                            ("manual_review_requested", "Manual review requested"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_user_id", models.UUIDField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=255)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_items",
                        to="submission.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "exception_inbox_item",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-created_at"],
                        name="exception_i_organiz_ed7713_idx",
                    ),
                    models.Index(
                        fields=["organization", "reason", "status"],
                        name="exception_i_organiz_e471d9_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invoice", "reason"),
                        name="uniq_inbox_item_per_invoice_reason",
                    )
                ],
            },
        ),
    ]
