# Generated by Django 5.1.15 on 2026-04-28 19:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_seed_roles_and_permissions'),
        ('submission', '0004_inbox_rls_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionCorrection',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_index=True, max_length=128)),
                ('original_value', models.TextField(blank=True)),
                ('corrected_value', models.TextField(blank=True)),
                ('extracted_by_engine', models.CharField(blank=True, max_length=128)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='submission.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'extraction_correction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'field_name'], name='extraction__organiz_75b584_idx'), models.Index(fields=['invoice', '-created_at'], name='extraction__invoice_88ef0c_idx'), models.Index(fields=['extracted_by_engine', 'field_name'], name='extraction__extract_3b6d14_idx')],
            },
        ),
    ]
