# Generated by Django 5.1.15 on 2026-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_correction_rls_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='adjustment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice_internal_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice_uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('standard', 'Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('refund_note', 'Refund Note'), ('self_billed_invoice', 'Self-Billed Invoice'), ('self_billed_credit_note', 'Self-Billed Credit Note'), ('self_billed_debit_note', 'Self-Billed Debit Note'), ('self_billed_refund_note', 'Self-Billed Refund Note'), ('self_billed', 'Self-Billed Invoice (legacy)')], default='standard', max_length=32),
        ),
    ]
