# Generated by Django 5.1.15 on 2026-04-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_lhdn_doc_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_id_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_id_value',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_id_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_id_value',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
