# Generated by Django 5.1.15 on 2026-04-29 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0014_inbox_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV upload"),
                            ("sql_accounting", "SQL Accounting"),
                            ("autocount", "AutoCount"),
                            ("xero", "Xero"),
                            ("quickbooks", "QuickBooks Online"),
                            ("shopify", "Shopify"),
                            ("woocommerce", "WooCommerce"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("credentials", models.JSONField(blank=True, default=dict)),
                (
                    "sync_cadence",
                    models.CharField(
                        choices=[
                            ("manual", "Manual only"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("auto_apply", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Never run"),
                            ("proposed", "Proposed (awaiting review)"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("reverted", "Reverted"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "connectors_integration_config",
                "ordering": ["connector_type"],
                "indexes": [
                    models.Index(
                        fields=["organization", "connector_type"],
                        name="connectors_org_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("organization", "connector_type"),
                        name="connectors_integration_config_uniq_org_type_active",
                    )
                ],
            },
        ),
    ]
