# Generated by Django 5.1.15 on 2026-04-29 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0002_rls_policies"),
        ("identity", "0014_inbox_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncProposal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_user_id", models.UUIDField()),
                ("proposed_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed (awaiting review)"),
                            ("applied", "Applied"),
                            ("reverted", "Reverted"),
                            ("expired", "Expired (revert window closed)"),
                            ("cancelled", "Cancelled by operator"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("applied_by_user_id", models.UUIDField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_by_user_id", models.UUIDField(blank=True, null=True)),
                ("diff", models.JSONField(default=dict)),
                ("applied_changes", models.JSONField(blank=True, default=dict)),
                (
                    "integration_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_proposals",
                        to="connectors.integrationconfig",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "connectors_sync_proposal",
                "ordering": ["-proposed_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterFieldConflict",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "master_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer master"),
                            ("item", "Item master"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("master_id", models.UUIDField(db_index=True)),
                ("field_name", models.CharField(max_length=64)),
                ("existing_value", models.TextField(blank=True, default="")),
                ("existing_provenance", models.JSONField(blank=True, default=dict)),
                ("incoming_value", models.TextField(blank=True, default="")),
                ("incoming_provenance", models.JSONField(blank=True, default=dict)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("keep_existing", "Keep existing value"),
                            ("take_incoming", "Take incoming value"),
                            ("keep_both_as_aliases", "Keep both (alias)"),
                            ("enter_custom_value", "Enter custom value"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("custom_value", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
                (
                    "sync_proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="connectors.syncproposal",
                    ),
                ),
            ],
            options={
                "db_table": "connectors_master_field_conflict",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MasterFieldLock",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "master_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer master"),
                            ("item", "Item master"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("master_id", models.UUIDField(db_index=True)),
                ("field_name", models.CharField(max_length=64)),
                ("locked_by_user_id", models.UUIDField()),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "connectors_master_field_lock",
                "ordering": ["-locked_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "master_type", "master_id"],
                        name="connectors_lock_master_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "master_type",
                            "master_id",
                            "field_name",
                        ),
                        name="connectors_lock_uniq_org_master_field",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="syncproposal",
            index=models.Index(
                fields=["integration_config", "-proposed_at"],
                name="conn_proposal_cfg_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncproposal",
            index=models.Index(
                fields=["organization", "status"], name="conn_proposal_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterfieldconflict",
            index=models.Index(
                fields=["organization", "resolved_at"],
                name="conn_conflict_org_unres_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="masterfieldconflict",
            index=models.Index(
                fields=["sync_proposal"], name="conn_conflict_proposal_idx"
            ),
        ),
    ]
