# Generated by Django 5.1.15 on 2026-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_rls_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='connector_type',
            field=models.CharField(choices=[('csv', 'CSV upload'), ('autocount', 'AutoCount'), ('sql_account', 'SQL Account'), ('sage_ubs', 'Sage UBS'), ('sql_accounting', 'SQL Accounting'), ('xero', 'Xero'), ('quickbooks', 'QuickBooks Online'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], db_index=True, max_length=32),
        ),
    ]
