# Generated by Django 5.1.15 on 2026-04-28 02:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.SlugField(max_length=128, unique=True)),
                ("vendor", models.CharField(max_length=64)),
                ("model_identifier", models.CharField(blank=True, max_length=128)),
                ("adapter_version", models.CharField(default="1", max_length=32)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("text_extract", "Text extract"),
                            ("vision_extract", "Vision extract"),
                            ("field_structure", "Field structure"),
                            ("embed", "Embed"),
                            ("classify", "Classify"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("degraded", "Degraded"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("cost_per_call_micros", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "engine",
                "ordering": ["capability", "name"],
                "indexes": [
                    models.Index(
                        fields=["capability", "status"],
                        name="engine_capabil_2501d5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EngineCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration_ms", models.IntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("timeout", "Timeout"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_class", models.CharField(blank=True, max_length=128)),
                ("cost_micros", models.IntegerField(default=0)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="extraction.engine",
                    ),
                ),
            ],
            options={
                "db_table": "engine_call",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["engine", "-started_at"],
                        name="engine_call_engine__d92618_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="engine_call_request_771a2f_idx"
                    ),
                    models.Index(
                        fields=["organization_id", "-started_at"],
                        name="engine_call_organiz_8be607_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EngineRoutingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("text_extract", "Text extract"),
                            ("vision_extract", "Vision extract"),
                            ("field_structure", "Field structure"),
                            ("embed", "Embed"),
                            ("classify", "Classify"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("priority", models.IntegerField(default=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("match_mime_types", models.CharField(default="*", max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing_rules",
                        to="extraction.engine",
                    ),
                ),
                (
                    "fallback_engine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="extraction.engine",
                    ),
                ),
            ],
            options={
                "db_table": "engine_routing_rule",
                "ordering": ["capability", "priority"],
                "indexes": [
                    models.Index(
                        fields=["capability", "is_active", "priority"],
                        name="engine_rout_capabil_7687c7_idx",
                    )
                ],
            },
        ),
    ]
