# Generated by Django 5.1.15 on 2026-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0002_seed_engines_and_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="credentials",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
