# Generated by Django 5.1.15 on 2026-04-28 21:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0007_notif_pref_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=2048)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('secret_prefix', models.CharField(db_index=True, max_length=16)),
                ('secret_hash', models.CharField(max_length=128)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_user_id', models.UUIDField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'integrations_webhook_endpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt', models.IntegerField(default=1)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure'), ('retrying', 'Retrying'), ('abandoned', 'Abandoned')], default='pending', max_length=16)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body_excerpt', models.CharField(blank=True, max_length=512)),
                ('error_class', models.CharField(blank=True, max_length=128)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'db_table': 'integrations_webhook_delivery',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='integration_organiz_3a90cc_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['organization', 'endpoint', '-queued_at'], name='integration_organiz_b4581f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_id'], name='integration_event_i_f884ad_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['outcome', '-queued_at'], name='integration_outcome_cd6a40_idx'),
        ),
    ]
