# Generated by Django 5.1.15 on 2026-04-27 22:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0003_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_channel",
                    models.CharField(
                        choices=[
                            ("web_upload", "Web upload"),
                            ("email_forward", "Email forward"),
                            ("whatsapp", "WhatsApp"),
                            ("api", "API"),
                            ("database_connector", "Database connector"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source_identifier",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("original_filename", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField()),
                ("file_mime_type", models.CharField(max_length=128)),
                ("s3_object_key", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("classifying", "Classifying"),
                            ("extracting", "Extracting"),
                            ("enriching", "Enriching"),
                            ("validating", "Validating"),
                            ("ready_for_review", "Ready for review"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("signing", "Signing"),
                            ("submitting", "Submitting"),
                            ("validated", "Validated by LHDN"),
                            ("rejected", "Rejected by LHDN"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=24,
                    ),
                ),
                ("state_transitions", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                (
                    "upload_timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_job",
                "ordering": ["-upload_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-upload_timestamp"],
                        name="ingestion_j_organiz_e00469_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="ingestion_j_organiz_5ee3c5_idx",
                    ),
                ],
            },
        ),
    ]
