# Generated by Django 5.1.15 on 2026-04-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_rls_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="extraction_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="extraction_engine",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
