# Generated by Django 5.1.15 on 2026-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_ingestionjob_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('classifying', 'Classifying'), ('extracting', 'Extracting'), ('enriching', 'Enriching'), ('validating', 'Validating'), ('ready_for_review', 'Ready for review'), ('awaiting_approval', 'Awaiting approval'), ('signing', 'Signing'), ('submitting', 'Submitting'), ('validated', 'Validated by LHDN'), ('rejected', 'Rejected by LHDN'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('bundle', 'Archive bundle')], db_index=True, default='received', max_length=24),
        ),
    ]
