# Generated by Django 5.1.15 on 2026-04-27 21:40

import apps.identity.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("tin", models.CharField(max_length=32, unique=True)),
                ("sst_number", models.CharField(blank=True, max_length=32)),
                ("registered_address", models.TextField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("billing_currency", models.CharField(default="MYR", max_length=3)),
                (
                    "trial_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("used_up", "Used up"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "subscription_state",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trialing",
                        max_length=16,
                    ),
                ),
                ("certificate_uploaded", models.BooleanField(default=False)),
                ("certificate_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "certificate_kms_key_alias",
                    models.CharField(blank=True, max_length=128),
                ),
                ("logo_url", models.URLField(blank=True)),
                (
                    "language_preference",
                    models.CharField(default="en-MY", max_length=10),
                ),
                (
                    "timezone",
                    models.CharField(default="Asia/Kuala_Lumpur", max_length=64),
                ),
            ],
            options={
                "db_table": "identity_organization",
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "identity_permission",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "preferred_language",
                    models.CharField(default="en-MY", max_length=10),
                ),
                (
                    "preferred_timezone",
                    models.CharField(default="Asia/Kuala_Lumpur", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_zerokey_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "identity_user",
            },
            managers=[
                ("objects", apps.identity.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="identity.permission"
                    ),
                ),
            ],
            options={
                "db_table": "identity_role",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "joined_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="identity.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.role",
                    ),
                ),
            ],
            options={
                "db_table": "identity_membership",
                "indexes": [
                    models.Index(
                        fields=["organization", "user"],
                        name="identity_me_organiz_f34854_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "organization"),
                        name="uniq_user_per_organization",
                    )
                ],
            },
        ),
    ]
