# Generated by Django 5.1.15 on 2026-04-28 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_seed_roles_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('key_prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=128)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_user_id', models.UUIDField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'identity_api_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='identity_ap_organiz_4b5110_idx'), models.Index(fields=['key_prefix'], name='identity_ap_key_pre_f9d299_idx')],
            },
        ),
    ]
