# Generated by Django 5.1.15 on 2026-04-29 04:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_membership_invitation_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationIntegration',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_key', models.CharField(max_length=64)),
                ('sandbox_credentials', models.JSONField(blank=True, default=dict)),
                ('production_credentials', models.JSONField(blank=True, default=dict)),
                ('active_environment', models.CharField(choices=[('sandbox', 'Sandbox / Dev'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('last_test_sandbox_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_sandbox_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_sandbox_detail', models.CharField(blank=True, max_length=512)),
                ('last_test_production_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_production_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_production_detail', models.CharField(blank=True, max_length=512)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'identity_organization_integration',
                'indexes': [models.Index(fields=['organization', 'integration_key'], name='identity_or_organiz_9fdb57_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'integration_key'), name='uniq_org_integration_key')],
            },
        ),
    ]
