# Generated by Django 5.1.15 on 2026-04-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_organization_integration_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='certificate_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='certificate_pem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='certificate_private_key_pem_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='certificate_serial_hex',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='certificate_subject_common_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
