# Generated by Django 5.1.15 on 2026-04-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_certificate_inline_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inbox_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
