# Generated by Django 5.1.15 on 2026-05-01 19:57

import apps.administration.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_user_onboarding_dismissed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcProvider',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='OIDC SSO', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('issuer', models.URLField(max_length=512)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', apps.administration.fields.EncryptedTextField(blank=True, default='')),
                ('scopes', models.CharField(default='openid email profile', max_length=512)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list)),
                ('jit_provision', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'identity_oidc_provider',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization',), name='uniq_oidc_provider_per_org')],
            },
        ),
    ]
