# Generated by Django 5.1.15 on 2026-05-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_oidc_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='msic_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
